defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

collections:
  tags:
    output: true
    permalink: tags/:path/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

url: https://uclcombiseminar.github.io
domain: uclcombiseminar.github.io


future: true
